# Generated by Django 5.1.6 on 2025-05-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbooking',
            name='route',
        ),
        migrations.AddField(
            model_name='route',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='bus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='busManagement.bus'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='busManagement.bus'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='busManagement.route'),
        ),
        migrations.AlterField(
            model_name='studentbooking',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='busManagement.bus'),
        ),
        migrations.AlterField(
            model_name='studentbooking',
            name='seats_booked',
            field=models.PositiveIntegerField(),
        ),
    ]
