# Generated by Django 5.1.6 on 2025-05-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.TextField(default=''),
        ),
    ]
