# Generated by Django 5.1.6 on 2025-05-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0002_remove_studentbooking_route_route_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
