# Generated by Django 5.1.6 on 2025-05-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0003_bus_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busManagement.driver'),
        ),
    ]
