# Generated by Django 5.1.6 on 2025-05-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0004_remove_bus_driver_name_remove_driver_bus_bus_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busManagement.driver'),
        ),
    ]
