# Generated by Django 5.2.1 on 2025-05-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0006_contact_alter_bus_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
    ]
