# Generated by Django 5.2.1 on 2025-06-01 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0007_rename_contact_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
