# Generated by Django 5.2.1 on 2025-06-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0012_remove_driver_user_profile_driver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
