# Generated by Django 5.2.1 on 2025-06-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busManagement', '0013_remove_driver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='studentbooking',
            name='student',
        ),
        migrations.AddField(
            model_name='studentbooking',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
